### ISSUE TITLE
Purpose for XYZ reorientation

### ISSUE THREAD

**Issue by JSLJ23** [JoshRackers/equivariant_electron_density#5]
https://github.com/JoshRackers/equivariant_electron_density/blob/97a27ccb833e843d5e89981bab4f8dedec86d9ae/utils.py#L83

Just wondering what this was for?

For context, I was generating densities with Psi4 using ωB97M-D3BJ/def2-TZVPPD and writing out the Psi4 Molecule coordinates as xyz files with `mol.save_xyz_file('name.xyz',1)`. If I extract the coordinates from these files, is the `yzx -> xyz` conversion still necessary?

**Comment by JoshRackers** [comment]
Yes, you still need to do the conversion. The reason is that spherical
harmonics in e3nn are not ordered in the standard order. I found it is
easier to account for this by permuting the input coordinates to match the
e3nn convention rather than permuting the output coefficients for every
basis function.

**Comment by JSLJ23** [comment]
https://github.com/JoshRackers/equivariant_electron_density/blob/97a27ccb833e843d5e89981bab4f8dedec86d9ae/utils.py#L529-L530
But doesn't this code here take care of the conversion of the ordering?

**Comment by JoshRackers** [comment]
Ah, yes, there are two issues that the current code fixes.
1. The ordering of the spherical harmonics (eg. -2, -1, 0, 1 ,2 vs. 0, 1,
-1, 2, -2). This is what the above line fixes.
2. The definition of the real spherical harmonics used in e3nn is different
than the standard (eg. wikipedia) or psi4. This is explained here:
https://docs.e3nn.org/en/stable/guide/change_of_basis.html. The permutation
of coordinates fixes this issue.

Hopefully this makes sense!

**Comment by JSLJ23** [comment]
Thank you for pointing that out too, it makes more sense now that I see they're addressing 2 separate issues.

Just for my understanding and also from the `e3nn` docs you reference, is the change of basis an either/or transformation in the sense that does it only need to be applied to either the inputs or the outputs?

So let's say if I want to keep the original XYZ input orientation, could I just apply the appropriate rotation matrix `D = o3.Irrep(2, 1).D_from_matrix(change_of_coord)` to convert the output coefficients to the canonical ordering?

**Comment by JSLJ23** [comment]
Another question regarding the density on grid evaluation.
https://github.com/JoshRackers/equivariant_electron_density/blob/97a27ccb833e843d5e89981bab4f8dedec86d9ae/utils.py#L489-L490
For these 2 lines, are they hard-coded to support spherical harmonic coefficients up to L=4?

**Comment by JoshRackers** [comment]
@JSLJ23 you are correct that you can apply the change of basis to either inputs or outputs. So yes, you could apply the appropriate rotation matrix to the output if you wanted. 

If you do this and can show that it gives the same result, please then put in pull request!

**Comment by JoshRackers** [comment]
And indeed, those lines are hard-coded for L=4. Not very elegant to say the least... sorry!

**Comment by JSLJ23** [comment]
> @JSLJ23 you are correct that you can apply the change of basis to either inputs or outputs. So yes, you could apply the appropriate rotation matrix to the output if you wanted.
> 
> If you do this and can show that it gives the same result, please then put in pull request!

I'll probably use your implementation of the change of basis from y,z,x to x,y,z for now but in future if I do get around to trying the other approach of applying the rotation matrices to the output spherical harmonics coefficients, I'll be sure to add it into a PR.

<br/>

> And indeed, those lines are hard-coded for L=4. Not very elegant to say the least... sorry!

No worries and thank you for clarifying as well, I will add a small change to that in a PR to make those dependent on the max L in the input `rs`.

**Comment by JSLJ23** [comment]
One more question from this same `utils.py` file.
https://github.com/JoshRackers/equivariant_electron_density/blob/97a27ccb833e843d5e89981bab4f8dedec86d9ae/utils.py#L81
I realized that the model is trained to predict this `pop` variable where it is defined above involving both the coefficient and this other normalisation factor.

I was wondering why this is the case? Is this better than training the model to just predict the coefficient and then obtain the normalisation factor value from a lookup table for each basis function per atom type?

Also, what exactly is this `norm` variable? I understand that it comes from the density fitting procedure but what exactly does it represent in the basis function?

**Comment by JoshRackers** [comment]
You can do either, but we found that training on "pop" rather than raw
coefficients is much better behaved.

The norm variable is just as it sounds: the normalization constant which
multiplies the whole basis function.

**Comment by JSLJ23** [comment]
Make sense, thank you for all explanations. 👍
